// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByJubNklXVFayKCf5nGlagtW-BKTEsI_4',
    appId: '1:146932480780:web:d28da7cc2801c465a4e729',
    messagingSenderId: '146932480780',
    projectId: 'software-521e8',
    authDomain: 'software-521e8.firebaseapp.com',
    storageBucket: 'software-521e8.appspot.com',
    measurementId: 'G-VDK4QERETC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSriJH6K8VSMV_MsdjRIk5PDiUswK2Zvw',
    appId: '1:146932480780:android:6447230f3dec69f3a4e729',
    messagingSenderId: '146932480780',
    projectId: 'software-521e8',
    storageBucket: 'software-521e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHG1HI4PiE9KaNFmIIZyiazEf5-oX-2k',
    appId: '1:146932480780:ios:5dd0d89fb51ad8d7a4e729',
    messagingSenderId: '146932480780',
    projectId: 'software-521e8',
    storageBucket: 'software-521e8.appspot.com',
    iosClientId: '146932480780-ig8nqcta2sibtri905hhcl9ec0gvbv5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.software',
  );
}
